apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - service-headless.yaml
  - statefullset.yaml

secretGenerator:
- name: pg-secret
  literals:
  - username=postgres
  - password=secret

namespace: db

generatorOptions:
  disableNameSuffixHash: true