apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
stringData:
   autoscrape.yaml: |
      - job_name: endpoints
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - action: drop
          regex: true
          source_labels:
          - __meta_kubernetes_pod_container_init
        - action: keep_if_equal
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_port
          - __meta_kubernetes_pod_container_port_number
        - source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_scrape
          action: keep
          regex: true
        - action: replace
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_scheme
          regex: (https?)
          target_label: __scheme__
        - action: replace
          regex: (.+)
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_path
          target_label: __metrics_path__
        - action: replace
          source_labels:
          - __address__
          - __meta_kubernetes_service_annotation_prometheus_io_port
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - source_labels:
          - __meta_kubernetes_service_name
          target_label: service
        - replacement: ${1}
          source_labels:
          - __meta_kubernetes_service_name
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: node