apiVersion: v1
kind: Service
metadata:
  name: loki-ruler
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ruler
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ruler