apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-tls
  namespace: es
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: node
  subject:
    organizations:
      - "Home"
    organizationalUnits:
      - "IT"
    localities:
      - "Ryazan"
    countries:
      - "RU"
  dnsNames:
  - localhost
  - es.home.local
  ipAddresses:
    - 127.0.0.1
  secretName: node-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io