auth_enabled: false
chunk_store_config:
  chunk_cache_config:
    memcached:
      batch_size: 256
      parallelism: 10
    memcached_client:
      host: chunk-cache-memcached.loki.svc.cluster.local
      service: memcache
common:
  compactor_address: loki-backend
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    s3:
      access_key_id: admin
      bucketnames: loki
      endpoint: minio-svc.minio.svc.cluster.local:9000
      insecure: true
      s3forcepathstyle: true
      secret_access_key: password
frontend:
  scheduler_address: query-scheduler-discovery.loki.svc.cluster.local.:9095
frontend_worker:
  scheduler_address: query-scheduler-discovery.loki.svc.cluster.local.:9095
index_gateway:
  mode: ring
ingester:
  chunk_idle_period: 2h
  chunk_target_size: 1536000
  max_chunk_age: 2h
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 30
  ingestion_rate_mb: 20
  max_cache_freshness_per_query: 10m
  max_query_parallelism: 8
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 10MB
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-memberlist
querier:
  engine:
    timeout: 300s
  query_timeout: 300s
query_range:
  align_queries_with_step: true
  cache_results: true
  parallelise_shardable_queries: false
  results_cache:
    cache:
      default_validity: 12h
      memcached_client:
        host: results-cache-memcached.loki.svc.cluster.local
        service: memcache
        timeout: 500ms
ruler:
  alertmanager_url: http://vmalertmanager-vm.monitoring.svc.cluster.local:9093
  remote_write:
    clients:
      victoria-metrics:
        name: vm
        url: http://vmsingle-vm.monitoring.svc.cluster.local:8429/vm/api/v1/write
    enabled: true
  storage:
    local:
      directory: /etc/loki/rules
    type: local
  wal:
    dir: /var/loki/loki-wal
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
  - from: "2022-01-11"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v12
    store: boltdb-shipper
server:
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 3100
  http_server_read_timeout: 310s
  http_server_write_timeout: 310s
storage_config:
  boltdb_shipper:
    active_index_directory: /var/loki/index
    shared_store: s3
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
  index_queries_cache_config:
    memcached:
      batch_size: 256
      parallelism: 10
    memcached_client:
      host: index-cache-memcached.loki.svc.cluster.local
      service: memcache