loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
backend:
  replicas: 1
write:
  replicas: 1
read:
  replicas: 1
minio:
  enabled: true

test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

