loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
    http_server_write_timeout: 310s
    http_server_read_timeout: 310s
    grpc_server_max_recv_msg_size: 104857600  # 100 Mb
    grpc_server_max_send_msg_size: 104857600  # 100 Mb
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
    s3:
      endpoint: minio-svc.minio.svc:9000
      secretAccessKey: password
      accessKeyId: admin
      s3ForcePathStyle: true
      insecure: true   
  ingester:
    chunk_encoding: snappy  
  limits_config:
    ingestion_rate_mb: 20
    ingestion_burst_size_mb: 30  
    per_stream_rate_limit: "3MB"
    per_stream_rate_limit_burst: "10MB"  

backend:
  replicas: 1
write:
  replicas: 1
read:
  replicas: 1

test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

