loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    instance_addr: 127.0.0.1
  query_range:
    parallelise_shardable_queries: false
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
    s3:
      endpoint: minio-svc.minio.svc:9000
      secretAccessKey: password
      accessKeyId: admin
      s3ForcePathStyle: true
      insecure: true   
  ingester:
    chunk_encoding: snappy  
  schema_config:
    configs:
    - from: "2022-01-11"
      index:
        period: 24h
        prefix: loki_index_
      store: boltdb-shipper
      object_store: s3
      schema: v12
write:
  replicas: 2
read:
  replicas: 1

test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

