
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
    spec:
      serviceAccountName: fluent-bit

      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"

      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.9.0
        imagePullPolicy: IfNotPresent
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: es-client
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        # - name: FLUENT_ELASTICSEARCH_SCHEME
        #   value: "http"
        # - name: FLUENTD_SYSTEMD_CONF
        #   value: disable
        ports:
        - name: http
          containerPort: 2020
          protocol: TCP

        livenessProbe:
          httpGet:
            path: /
            port: http

        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http

        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi

        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/machine-id
          name: etcmachineid
          readOnly: true

      volumes:
      - name: config
        configMap:
          name: fluent-bit-cfg
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
      - hostPath:
          path: /etc/machine-id
          type: File
        name: etcmachineid
