apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: fluent-bit
  name: fluent-bit
  namespace: monitoring
spec:
  endpoints:
  - port: http
    path: /api/v1/metrics/prometheus
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit-metrics
  namespaceSelector:
    matchNames:
    - logging
