apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alert
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
data:
  loki-alert.yaml: |
     groups:
        - name: loki-rules
          rules:
            - alert: error show
              expr: sum(rate({app="loki", component="read"} |= `level=error` [1h])) by (app) * 60 > 1
              for: 1s
              labels:
                severity: info
                type: loki-alert
              annotations:
                summary: app {{$labels.app}} component {{$labels.component}} has a lot of error