apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
data:
  loki-rules.yaml: |
    groups:
        - name: loki-rules
          rules:
            - record: error:loki:sum_rate
              expr: sum(rate({app="loki", component="read"} |= `level=error` [1h])) by (app) * 60 > 1
              labels:
                type: loki-alert

            
  
  

     
            