apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator
  namespace: argocd
  labels:
    app: monitoring
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: monitoring/operator
    repoURL: 'https://github.com/vladoz77/argocd'
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  sources: []
  project: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
