apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  labels:
    app: utilits
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: utils/reloader/manifests
    repoURL: 'https://github.com/vladoz77/argocd'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: utilits
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
