apiVersion: v1
kind: ConfigMap
metadata:
    name: kibana-config
    namespace: logging
data:
    kibana.yml: |-
        server.host: "0.0.0.0"
        server.publicBaseUrl: http://0.0.0.0:5601

        elasticsearch:
          hosts: ${ELASTICSEARCH_URL}
          username: ${ELASTICSEARCH_USERNAME}
          password: ${ELASTICSEARCH_PASSWORD}
        logging:
          events:
            request: "!"
            response: "!"