apiVersion: v1
kind: Service
metadata:
  name: kube-proxy-metrics-svc
  namespace: kube-system
  labels:
    app: kube-proxy-metrics-svc
    jobLabel: kube-proxy
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 10249
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
  clusterIP: None