apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: monitoring-stack
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/vladoz77/argocd.git'
    path: monitoring-single/apps
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true