apiVersion: v1
kind: ConfigMap
metadata:
  name: record-rules-config
  namespace: monitoring-test
data:
  record.yaml: |
    groups:
    - name: record
      rules:
      - record: job:node_memory_MemFree_bytes:percent 
        expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)    
  