apiVersion: v1
kind: ConfigMap
metadata:
  name: scrape-config
  namespace: monitoring
data:
  scrape-config.yml: |
    - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      job_name: apiserver
      kubernetes_sd_configs:
      - namespaces:
          names:
          - default
        role: endpoints
      relabel_configs:
      - action: keep
        regex: apiserver
        source_labels:
        - __meta_kubernetes_service_label_component
      - action: keep
        regex: https
        source_labels:
        - __meta_kubernetes_endpoint_port_name
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: service
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - replacement: https
        target_label: endpoint
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      job_name: kubelet
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/$1/proxy/metrics
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__
      - source_labels:
        - __meta_kubernetes_node_name
        target_label: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      honor_timestamps: false
      job_name: cadvisor
      kubernetes_sd_configs:
      - role: node
      metric_relabel_configs:
      - action: drop
        regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
        source_labels:
        - __name__
      - action: drop
        regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
        source_labels:
        - __name__
      - action: drop
        regex: container_memory_(mapped_file|swap)
        source_labels:
        - __name__
      - action: drop
        regex: container_(file_descriptors|tasks_state|threads_max)
        source_labels:
        - __name__
      - action: drop
        regex: container_spec.*
        source_labels:
        - __name__
      - action: drop
        regex: .+;
        source_labels:
        - id
        - pod
      relabel_configs:
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__
      - replacement: cadvisor
        target_label: job
      - source_labels:
        - __meta_kubernetes_node_name
        target_label: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - honor_labels: true
      job_name: kube-proxy
      kubernetes_sd_configs:
      - namespaces:
          names:
          - kube-system
        role: pod
      relabel_configs:
      - action: keep
        regex: kube-proxy.+
        source_labels:
        - __meta_kubernetes_pod_name
      - action: replace
        regex: (.+?)(\\:\\d+)?
        replacement: $1:10249
        source_labels:
        - __address__
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: job
    - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      honor_labels: true
      job_name: kube-controller-manager
      kubernetes_sd_configs:
      - namespaces:
          names:
          - kube-system
        role: pod
      relabel_configs:
      - action: keep
        regex: kube-controller-manager.+
        source_labels:
        - __meta_kubernetes_pod_name
      - action: replace
        regex: (.+?)(\\:\\d+)?
        replacement: $1:10257
        source_labels:
        - __address__
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: job
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      honor_labels: true
      job_name: kube-scheduler
      kubernetes_sd_configs:
      - namespaces:
          names:
          - kube-system
        role: pod
      relabel_configs:
      - action: keep
        regex: kube-scheduler.+
        source_labels:
        - __meta_kubernetes_pod_name
      - action: replace
        regex: (.+?)(\\:\\d+)?
        replacement: $1:10259
        source_labels:
        - __address__
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: job
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - honor_labels: true
      job_name: node-exporter
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: monitoring;node-exporter-service;http-metrics
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: job
      - source_labels:
        - __meta_kubernetes_endpoint_node_name
        target_label: node
    - honor_labels: true
      job_name: kube-state-metrics
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: monitoring;kube-state-metrics;http-metrics
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: job