---
# Source: victoria-metrics-alert/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmalert-victoria-metrics-alert
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-metrics-alert
---
# Source: victoria-metrics-alert/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vmalert-clusterrolebinding
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-metrics-alert
subjects:
  - kind: ServiceAccount
    name: vmalert-victoria-metrics-alert
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: vmalert-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: victoria-metrics-alert/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  vmalert
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-metrics-alert
rules: []
---
# Source: victoria-metrics-alert/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vmalert
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-metrics-alert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vmalert
subjects:
- kind: ServiceAccount
  name: vmalert-victoria-metrics-alert
  namespace: monitoring
---
# Source: victoria-metrics-alert/templates/server-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-metrics-alert
  name: vmalert
spec:
  ports:
    - name: http
      port: 8880
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: victoria-metrics-alert
  type: "ClusterIP"
---
# Source: victoria-metrics-alert/templates/server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmalert
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-metrics-alert
spec:
  minReadySeconds: 0
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics-alert
  template:
    metadata:
      labels:
        app.kubernetes.io/name: victoria-metrics-alert
    spec:
      serviceAccountName: vmalert-victoria-metrics-alert
      containers:
        - name: victoria-metrics-alert-server
          image: "victoriametrics/vmalert:v1.96.0"
          args:
            - -rule=/config/*.yaml
            - -datasource.url=http://vmsingle.monitoring.svc.cluster.local:8428
            - -notifier.url=
            - -remoteRead.url=
            - -remoteWrite.url=http://vmsingle.monitoring.svc.cluster.local:8428
            - -envflag.enable=true
            - -envflag.prefix=VM_
            - -loggerFormat=json
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8880
          
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          
          volumeMounts:
            - name: record-rules
              mountPath: /config/record.yaml
              subPath: record.yaml
    
            
          resources:
            {}
      volumes:
        - name: record-rules
          configMap:
            name: record-rules-config
        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: record-rules-config
  namespace: monitoring
data:
  record.yaml: |
    groups:
    - name: record
      rules:
      - record: job:node_memory_MemFree_bytes:percent 
        expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes) 
