apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cfg
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    domain = mon.home.local
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    serve_from_sub_path = true

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: victoria-metrics
      access: proxy
      editable: true
      orgId: 1
      type: prometheus
      url: http://vmsingle-vm.monitoring.svc.cluster.local:8429/vm
      version: 1

    - name: loki
      access: proxy
      editable: true
      orgId: 1
      type: loki
      url: http://loki-gateway.loki.svc
      version: 1
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: '"trace_id": "(\w+)"'
            name: TraceID
            url: '$${__value.raw}'
            urlDisplaylabel: 'View Trace'

    - name: Tempo
      type: tempo
      uid: tempo
      access: proxy
      url: http://tempo-query-frontend.tracing.svc.cluster.local:3100

  dashboards.yaml: |-
    apiVersion: 1
    providers: 
      - name: victoria-metrics
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
        type: file
