apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-st
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana-app
  serviceName: grafana-st-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      volumes:
        - name: grafana-config-v
          configMap:
            name: grafana-ini
      containers:
      - name: grafana
        image: grafana/grafana:10.0.1
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-config-v
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
  volumeClaimTemplates:
  - metadata:
      name: grafana-storage
    spec:
      storageClassName: nfs-client
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-st-svc
  namespace: monitoring
spec:
  selector:
    app: grafana-app
  ports:
  - port: 3000
    targetPort: grafana
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-st-svc-sys
  namespace: monitoring
spec:
  selector:
    app: grafana-app
  ports:
  - port: 3000
    targetPort: grafana

