apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: monitoring
data:
  grafana.ini: |-
    [server]
    domain = mon.home.local
    root_url = %(protocol)s://%(domain)s:80/grafana/
    serve_from_sub_path = true