apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
  labels:
    app.kubernetes.io/name: reloader
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: reloader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reloader
        chart: "reloader-1.0.97"
    spec:
      containers:
      - image: "ghcr.io/stakater/reloader:v1.0.97"
        imagePullPolicy: IfNotPresent
        name: reloader
        ports:
        - name: http
          containerPort: 9090
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /live
            port: http
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
          initialDelaySeconds: 10
      securityContext: 
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: reloader
