# Source: victoria-metrics-alert/templates/alertmanager-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmalert-alertmanager-alertmanager-config
  namespace: monitoring-test
  labels:
    app: alertmanager
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: vmalert
    helm.sh/chart: victoria-metrics-alert-0.9.4
    app.kubernetes.io/managed-by: Helm
data:
  alertmanager.yaml: |
    
    global:
      resolve_timeout: 5m
    receivers:
    - name: devnull
    route:
      group_by:
      - alertname
      group_interval: 10s
      group_wait: 30s
      receiver: devnull
      repeat_interval: 24h
---

# Source: victoria-metrics-alert/templates/alertmanager-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmalert-alertmanager
  namespace: monitoring-test
  labels:
    app: alertmanager
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: vmalert
    helm.sh/chart: victoria-metrics-alert-0.9.4
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Mi"
---

# Source: victoria-metrics-alert/templates/alertmanager-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring-test
  labels:
    app: alertmanager
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: vmalert
    helm.sh/chart: victoria-metrics-alert-0.9.4
    app.kubernetes.io/managed-by: Helm
  name: vmalert-alertmanager
spec:
  ports:
    - name: web
      port: 9093
      targetPort: web
      protocol: TCP
  selector:
    app: alertmanager
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: vmalert

---
# Source: victoria-metrics-alert/templates/alertmanager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmalert-alertmanager
  namespace: monitoring-test
  labels:
    app: alertmanager
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: vmalert
    helm.sh/chart: victoria-metrics-alert-0.9.4
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
      app.kubernetes.io/name: victoria-metrics-alert
      app.kubernetes.io/instance: vmalert
  strategy:
    # Must be "Recreate" when we have a persistent volume
    type: Recreate
  template:
    metadata:
      labels:
        app: alertmanager
        app.kubernetes.io/name: victoria-metrics-alert
        app.kubernetes.io/instance: vmalert
        helm.sh/chart: victoria-metrics-alert-0.9.4
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: vmalert-victoria-metrics-alert
      containers:
        - name: victoria-metrics-alert-alertmanager
          securityContext:
            null
          image: "prom/alertmanager:v0.25.0"
          args:
            - --config.file=/config/alertmanager.yaml
            - --storage.path=/data
            - --data.retention=120h
            - --web.listen-address=0.0.0.0:9093
            - --cluster.advertise-address=$(POD_IP):6783
          ports:
            - name: web
              containerPort: 9093
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
          
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
          
          volumeMounts:
            - name: storage
              mountPath: /data
            - name: config
              mountPath: /config
              readOnly: true
          
          resources: {}
      
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: vmalert-alertmanager
        - name: config
          configMap:
            name: vmalert-alertmanager-alertmanager-config
