apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: logging
  source:
    repoURL: 'https://github.com/vladoz77/argocd'
    path: logging/fluentbit
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
