apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
data:
  config.yaml: |
    server:
      http_listen_port: 3100
    
    auth_enabled: false
    
    chunk_store_config:
      max_look_back_period: 0s
    
    common:
      compactor_address: http://loki-compactor:3100
      path_prefix: /var/loki
      replication_factor: 1
          
    compactor:
      apply_retention_interval: 1h
      compaction_interval: 5m
      retention_delete_worker_count: 500
      retention_enabled: true
      shared_store: s3
      working_directory: /var/loki/compactor
    
    distributor:
      ring:
        kvstore:
          store: memberlist
    
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      tail_proxy_url: http://loki-querier:3100
    
    frontend_worker:
      frontend_address: loki-query-frontend-headless:9095
    
    ingester:
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal
    
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    
    memberlist:
      join_members:
      - loki-memberlist
    
    query_range:
      parallelise_shardable_queries: false
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            ttl: 24h
    
    ruler:
      alertmanager_url: http://alertmanager-service.monitoring.svc:9093
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      storage:
        type: s3
        s3:
          bucketnames: ruler
        
    
    runtime_config:
      file: /var/loki-runtime/runtime.yaml
    
    schema_config:
      configs:
      - from: "2020-09-07"
        object_store: s3
        schema: v12
        store: boltdb-shipper
        index:
          period: 24h
          prefix: loki_index_

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        build_per_tenant_index: true
        cache_ttl: 24h
        shared_store: s3
      aws:
        access_key_id: admin
        bucketnames: chunks
        endpoint: minio-svc.minio.svc.cluster.local:9000
        insecure: true
        s3forcepathstyle: true
        secret_access_key: password
        
    

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-runtime
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
data:
  runtime.yaml: |
    {}