nameOverride: minio
fullnameOverride: minio

mode: distributed
auth:
  rootUser: admin
  rootPassword: password

defaultBuckets: loki, tempo

extraEnvVars:
  - name: MINIO_PROMETHEUS_URL
    value: vmsingle.monitoring.svc.cluster.local:8428

statefulset:
  # statefulset.replicaCount Number of pods per zone (only for MinIO&reg; distributed mode). Should be even and `>= 4`
  replicaCount: 2
  # statefulset.zones Number of zones (only for MinIO&reg; distributed mode)
  zones: 1
  # statefulset.drivesPerNode Number of drives attached to every node (only for MinIO&reg; distributed mode)
  drivesPerNode: 2

service:
  annotations:
    prometheus.io/port: '9000'
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/minio/v2/metrics/cluster'

ingress:
  enabled: true
  hostname: minio-test.dev.local
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  extraTls:
    - hosts:
      - minio-test.dev.local
      secretName: minio-test-tls
