apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm
  namespace: monitoring
spec:
  podMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8429"
      prometheus.io/path: "/vm/metrics"
  image:
    tag: v1.94.0
  extraArgs:
    http.pathPrefix: /vm
    maxLabelsPerTimeseries: "50"
    dedup.minScrapeInterval: 60s
  retentionPeriod: "30"
  # logFormat: json
  removePvcAfterDelete: true
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  resources:
    limits:
      cpu: 1200m
      memory: 1500Mi
    requests:
      cpu: 500m
      memory: 500Mi
