apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-config-cm
  namespace: monitoring
data:
  calico-config.yml: |
    #Calico
    - job_name: Calico
      honor_labels: true
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - calico-system
      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_service_label_k8s_app]
        regex:
        - calico-kube-controllers
        - calico-typha
        - calico-felix
      - action: keep
        source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: metrics-port
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - source_labels: [__meta_kubernetes_service_name]
        target_label: job