---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8429"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/version: "v1.96.0"
  name: vmagent
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 8429
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: vmagent
  type: "ClusterIP"