---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmagent
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/version: "v1.96.0"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-clusterrole
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/version: "v1.96.0"
rules:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmagent-clusterrolebinding
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/version: "v1.96.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmagent-clusterrole
subjects:
  - kind: ServiceAccount
    name: vmagent
    namespace: monitoring

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8429"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/version: "v1.96.0"
  name: vmagent
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 8429
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: vmagent
  type: "ClusterIP"

---
kind: Service
apiVersion: v1
metadata:
  name:  vmagent-headless
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/version: "v1.96.0"
  namespace: monitoring
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: vmagent
  type:  ClusterIP
  ports:
    - name: http
      port: 8429
      protocol: TCP
      targetPort: http

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vmagent
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/version: "v1.96.0"
spec:
  replicas: 1
  serviceName: vmagent
  selector:
    matchLabels:
      app.kubernetes.io/name: vmagent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vmagent
    spec:
      serviceAccountName: vmagent
      containers:
        - name: victoria-metrics-agent
          image: "victoriametrics/vmagent:v1.96.0"
          workingDir: /
          args:
            - -promscrape.config=/config/scrape.yml
            - -remoteWrite.tmpDataPath=/tmpData
            - -remoteWrite.url=http://vmsingle.monitoring-test.svc.cluster.local:8428/api/v1/write
            - -envflag.enable=true
            - -envflag.prefix=VM_
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8429
          
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          
          resources: 
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi

          volumeMounts:
            - name: tmpdata
              mountPath: /tmpData
            - name: config
              mountPath: /config/
            - name: autoscrape-config
              mountPath: /custom-configs/autoscrape-config.yml
              subPath: autoscrape-config.yml
            - name: calico-config
              mountPath: /custom-configs/calico-config.yml
              subPath: calico-config.yml
            - name: istio-config
              mountPath: /custom-configs/istio-config.yml
              subPath: istio-config.yml
          
      volumes:
        - name: config
          configMap:
            name: vmagent-config
        - name: autoscrape-config
          configMap:
            name: autoscrape-config
        - name: calico-config
          configMap:
            name: calico-config-cm
        - name: istio-config
          configMap:
            name: istio-config-cm
  
  volumeClaimTemplates:
  - metadata:
      name: tmpdata
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "10Gi"
