apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/version: "v1.96.0"
data:
  scrape.yml: |
    global:
      scrape_interval: 10s
    
    scrape_config_files:
      - /custom-configs/*.yml
    
    scrape_configs:
    #apiserver
    - job_name: apiserver
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
            names:
            - default
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_service_label_component]
        regex: apiserver
      - action: keep
        source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: https
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - target_label: endpoint
        replacement: https
    
    #kubelet
    - job_name: kubelet
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/$1/proxy/metrics
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__
      - source_labels: [__meta_kubernetes_node_name]
        target_label: node

    # cadvisor
    - job_name: cadvisor
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      honor_timestamps: false
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      - target_label: job
        replacement: cadvisor
      - source_labels: [__meta_kubernetes_node_name]
        target_label: node
      metric_relabel_configs:
        - action: drop
          source_labels: [__name__]
          regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
        - action: drop
          source_labels: [__name__]
          regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
        - action: drop
          source_labels: [__name__]
          regex: container_memory_(mapped_file|swap)
        - action: drop
          source_labels: [__name__]
          regex: container_(file_descriptors|tasks_state|threads_max)
        - action: drop
          source_labels: [__name__]
          regex: container_spec.*
        - action: drop
          source_labels: [id, pod]
          regex: .+;

    #kube-proxy
    - job_name: kube-proxy
      honor_labels: true
      kubernetes_sd_configs:
      - role: pod
        namespaces:
            names:
            - kube-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_k8s_app]
        regex: kube-proxy
        action: keep
      - source_labels:
        - __address__
        regex: (.+?)(\\:\\d+)?
        replacement: $1:10249
        action: replace
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels: 
        - __meta_kubernetes_pod_label_app
        target_label: job

    #kube-controller-manager
    - job_name: kube-controller-manager
      honor_labels: true
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: pod
        namespaces:
            names:
            - kube-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        regex: kube-controller-manager
        action: keep
      - source_labels:
        - __address__
        regex: (.+?)(\\:\\d+)?
        replacement: $1:10257
        action: replace
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels: 
        - __meta_kubernetes_pod_label_app
        target_label: job

    # kube-scheduler
    - job_name: kube-scheduler
      honor_labels: true
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - kube-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        regex: kube-scheduler
        action: keep
      - source_labels:
        - __address__
        regex: (.+?)(\\:\\d+)?
        replacement: $1:10259
        action: replace
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels: 
        - __meta_kubernetes_pod_label_app
        target_label: job

    #Node-exporter    
    - job_name: node-exporter
      honor_labels: true
      kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - monitoring
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
          regex: node-exporter-service
          action: keep
        - action: keep
          source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: http-metrics
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        # - source_labels: [__meta_kubernetes_service_name]
        #   target_label: service
        - source_labels: [__meta_kubernetes_service_name]
          target_label: job
        - source_labels: [__meta_kubernetes_endpoint_node_name]
          target_label: node

    #Kube-state-metrics
    - job_name: kube-state-metrics
      honor_labels: true
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
              names:
              - monitoring
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
          regex: kube-state-metrics
          action: keep
        - action: keep
          source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: http-metrics
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        # - source_labels: [__meta_kubernetes_service_name]
        #   target_label: service
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_service_name]
          target_label: job
