apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-client-provisioner-config
  namespace: default
data:
  PROVISIONER_NAME: cluster.local/nfs-subdir-external-provisioner
  NFS_SERVER: 192.168.59.1
  NFS_PATH: /data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client
              mountPath: /persistentvolumes
          envFrom:
            - configMapRef:
                name: nfs-client-provisioner-config
          resources: {}

      volumes:
        - name: nfs-client
          nfs:
            server: 192.168.59.1
            path: /data

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: cluster-local/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"