replicaCount: 1
deployment:
  enabled: false
statefulset:
  enabled: true
  clusterMode: true

nameOverride: vmagent
fullnameOverride: vmagent

# extraArgs:
#   promscrape.cluster.replicationFactor: 2
#   promscrape.cluster.memberURLTemplate: http://vmagent.dev.local-%d:8429/targets

remoteWriteUrls: 
  - "http://vmsingle.monitoring-test.svc.cluster.local:8428/api/v1/write"

service:
  enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8429"
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  hosts:
    - name: vmagent.dev.local
      path: / 
      port: http
  tls:
    - secretName: vmagent-ingress-tls
      hosts:
        - vmagent.dev.local

persistence:
  enabled: true
  size: 10Gi

extraVolumes:
  - name: base-scrape-config
    configMap:
      name: scrape-config
extraVolumeMounts:
  - name: base-scrape-config
    mountPath: /config/scrape-config.yml
    subPath: scrape-config.yml

config:
  global:
    scrape_interval: 30s
  scrape_config_files:
    - /config/*.yml