nameOverride: vm
fullnameOverride: vm

serviceAccount:
  create: false
defaultRules:
  create: true

vmsingle:
  enabled: true
  spec:
    image:
      tag: v1.93.4
    replicaCount: 1
    storage:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

alertmanager:
  enabled: true
  spec:
    image:
      tag: v0.25.0
    storage:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-storage
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

vmalert:
  enabled: true
  spec:
    image:
      tag: v1.93.4

vmagent:
  enabled: true
  spec:
    image:
      tag: v1.93.4

grafana:
  enabled: true
  additionalDataSources:
  - name: loki
    access: proxy
    editable: true
    jsonData:
      tlsSkipVerify: true
    orgId: 1
    type: loki
    url: http://loki-gateway.loki.svc.cluster.local
    version: 1


