apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  labels:
    app: logging
spec:
  destination:
    name: ''
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    path: logging/fluent-bit
    repoURL: 'https://github.com/vladoz77/argocd'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: logging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
