apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  labels:
    app: logging
spec:
  destination:
    name: ''
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    path: logging/kibana
    repoURL: 'https://github.com/vladoz77/argocd'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
