apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: db
resources:
  - service.yaml
  - ingress.yaml
  - deployment.yaml
  - pvc.yaml

secretGenerator:
- name: secret-pgadmin
  literals:
  - PGADMIN_DEFAULT_EMAIL=user@domain.com
  - PGADMIN_DEFAULT_PASSWORD=password

configMapGenerator:
- name: pgadmin-cofigmap
  literals:
  - PGADMIN_PORT="80"
  - PGADMIN_CONFIG_SERVER_MODE="False"

generatorOptions:
  disableNameSuffixHash: true