apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pgadmin
spec:
  # storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce