apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: postgres
spec:
  project: default
  source:
    path: postgres/manifests
    repoURL: 'https://github.com/vladoz77/argocd'
    targetRevision: HEAD
    directory:
      recurse: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: db
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true