apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  # finalizers:
  #    - resources-finalizer.argocd.argoproj.io
  labels:
    app: otel-collector
spec:
  project: default
  source:
    chart: opentelemetry-collector
    repoURL:  https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.88.0
    helm:
      valuesObject:
        fullnameOverride: otel-collector
        mode: deployment
        image:
          repository: otel/opentelemetry-collector-k8s
        config:
          receivers:
            jaeger:
              protocols:
                grpc:
                  endpoint: ${env:MY_POD_IP}:14250
                thrift_http:
                  endpoint: ${env:MY_POD_IP}:14268
                thrift_compact:
                  endpoint: ${env:MY_POD_IP}:6831
            otlp:
              protocols:
                grpc:
                  endpoint: ${env:MY_POD_IP}:4317
                http:
                  endpoint: ${env:MY_POD_IP}:4318

          exporters:
            otlp:
              endpoint: tempo-distributor:4317
              tls:
                insecure: true
            # debug:
            #     loglevel: info
          service:
            pipelines:
              traces: # here, we add the receivers and exporters accordingly
                  exporters:
                    - otlp
                    # - debug
                  processors:
                    - memory_limiter
                    - batch
                  receivers:
                    - otlp
                    - jaeger
              metrics: null
              logs: null
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tempo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true