apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-nginx
  namespace: default
spec:
  isCA: true
  commonName: ca-nginx
  secretName: ca-nginx
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Create CA Issure 
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer-nginx
  namespace: default
spec:
  ca:
    secretName: ca-nginx




