apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
  namespace: cert-manager
spec:
  isCA: true
<<<<<<< HEAD
  commonName: kube-ca
=======
  subject:
    organizations:
      - "Vlad's homelab"
    organizationalUnits:
      - "Home lab"
    localities:
      - "Ryazan"
    countries:
      - "RU"
  commonName: ca
>>>>>>> 5a04b82ca877ec544a09639fc7c1957d6fe677a6
  secretName: ca-secret
  privateKey:
    algorithm: ECDSA
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Create CA Issure 
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-secret




