apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuard
  namespace: default
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - home
  secretName: kuard-cert
  dnsNames:
  - web.home.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
    
