apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web
  namespace: default
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - home
  secretName: web-cert
  dnsNames:
  - web.home.local
  issuerRef:
    name: ca-issuer-nginx
    kind: Issuer
    group: cert-manager.io
    
