apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web
  namespace: default
spec:
  secretName: web-cert
  dnsNames:
  - web.home.local
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
