apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-sts
  namespace: monitoring
  annotations:
    reloader.stakater.com/auto: "true"
    configmap.reloader.stakater.com/reload: "prometheus-config"
spec:
  selector:
    matchLabels:
      app: prometeus-app
  serviceName: prometeus-app-service
  replicas: 1
  template:
    metadata:
      labels:
        app: prometeus-app
    spec:
      priorityClassName: low-priority
      serviceAccountName: prometheus
      volumes:
        - name: prometheus-config-v
          configMap:
            name: prometheus-config
      containers:
      - name: prometeus
        image: prom/prometheus:v2.45.0
        args: 
          - '--web.listen-address=0.0.0.0:9090'
          - '--config.file=/etc/prometheus/prometheus.yaml'
          - '--storage.tsdb.path=/prometheus'
          - '--web.external-url=http://mon.home.local:80/prometheus/'
          - '--web.console.libraries=/usr/share/prometheus/console_libraries'
          - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
        - containerPort: 9090
          name: prometeus
        volumeMounts:
        - name: data
          mountPath: /prometeheus
        - name: prometheus-config-v
          mountPath: /etc/prometheus/prometheus.yaml
          subPath: prometheus.yaml
        
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: nfs-client
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: prometeus-app-service
  namespace: monitoring
spec:
  clusterIP: None
  selector:
    app: prometeus-app
  ports:
  - port: 9090
    name: prometeus

---
apiVersion: v1
kind: Service
metadata:
  name: prometeus-app-service-sys
  namespace: monitoring
spec:
  selector:
    app: prometeus-app
    statefulset.kubernetes.io/pod-name: prometheus-sts-0
  ports:
  - port: 9090
    name: prometheus
