---
# Source: prometheus-elasticsearch-exporter/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: es-exporter-service
  namespace: es
  labels:
    app: es-exporter-service
    jobLabel: es-exporter
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9108
      protocol: TCP
  selector:
    app: es-exporter
---
# Source: prometheus-elasticsearch-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: es
  name: es-exporter
  labels:
    app: es-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: es-exporter
    spec:
      serviceAccountName: default
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: exporter
          image: "quay.io/prometheuscommunity/elasticsearch-exporter:v1.6.0"
          imagePullPolicy: IfNotPresent
          command:
            - elasticsearch_exporter
            - '--log.format=json'
            - '--log.level=info'
            - '--es.uri=https://admin:admin@es-cluster-master:9200'
            - '--es.all'
            - '--web.telemetry-path=/metrics'
          
          env: 
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          
          ports:
            - containerPort: 9108
              name: http
          
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 5
          
          # resources:
          #   limits: 
          #     cpu: 50m
          #     memory: 64Mi
          #   requests:
          #     cpu: 25m
          #     memory: 32Mi

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: es-exporter
  name: es-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: http-metrics
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: es-exporter-service
  namespaceSelector:
    matchNames:
    - es

