apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: es-exporter
  name: es-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: http
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-elasticsearch-exporter
  namespaceSelector:
    matchNames:
    - es