apiVersion: v1
kind: Service
metadata:
  name: es-cluster-master-metrics
  labels:
    app.kubernetes.io/name: es-cluster-master-metrics
  namespace: es
spec:
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/name: opensearch
  ports:
  - name: http-metrics
    port: 9200
    targetPort: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: es-cluster-data-metrics
  labels:
    app.kubernetes.io/name: es-cluster-data-metrics
  namespace: es
spec:
  selector:
    app.kubernetes.io/component: data
    app.kubernetes.io/name: opensearch
  ports:
  - name: http-metrics
    port: 9200
    targetPort: 9200

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: es-cluster
  name: es-cluster
  namespace: es
spec:
  endpoints:
  - interval: 15s
    port: http-metrics
    path: /_prometheus/metrics
    scheme: https
    tlsConfig:
        insecureSkipVerify: true
        ca:
          secret:
            name: opensearch-certs
            key: ca-root.pem
        cert:
          secret:
            name: opensearch-certs
            key: node.pem
        keySecret:
          name: opensearch-certs
          key: node-key.pem

  jobLabel: jobLabel
  
  selector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - data
          - master
      - key: app.kubernetes.io/name
        operator: In
        values:
          - opensearch
  namespaceSelector:
    matchNames:
    - es