apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: es-cluster
  name: es-cluster
  namespace: es
spec:
  endpoints:
  - interval: 15s
    port: http
    path: /_prometheus/metrics
    scheme: https
    tlsConfig:
        insecureSkipVerify: true
    basicAuth:
      password:
        name: admin-user
        key: password
      username:
        name: admin-user
        key: username
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/component: master
  namespaceSelector:
    matchNames:
    - es