apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: monitoring-test
  labels:
    app.kubernetes.io/name: vmagent
data:
  scrape.yml: |
    
    global:
      scrape_interval: 10s

    scrape_configs:
    # kube-apiservice
    - job_name: apiserver
      kubernetes_sd_configs:
      - role: endpoints
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
        regex: default;kubernetes;https
        action: keep
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - target_label: endpoint
        replacement: https

    # kubernetes-scheduler  
    - job_name: kube-scheduler
      kubernetes_sd_configs:
      - role: endpoints
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
        regex: kube-system;kube-scheduler-service;metrics
        action: keep
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container

    # kube-controller
    - job_name: kube-controller
      kubernetes_sd_configs:
      - role: endpoints
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      relabel_configs:
      - action: keep
        source_labels: 
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
        regex: kube-system;kube-controller-manager-service;metrics
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container

    # kubelet  
    - job_name: kubelet
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/$1/proxy/metrics
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__
      - source_labels: [__meta_kubernetes_node_name]
        target_label: node


      
    # cadvisor
    - job_name: cadvisor
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      honor_timestamps: false
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      - target_label: job
        replacement: cadvisor
      - source_labels: [__meta_kubernetes_node_name]
        target_label: node
        
      metric_relabel_configs:
        - action: drop
          source_labels: [__name__]
          regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
        - action: drop
          source_labels: [__name__]
          regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
        - action: drop
          source_labels: [__name__]
          regex: container_memory_(mapped_file|swap)
        - action: drop
          source_labels: [__name__]
          regex: container_(file_descriptors|tasks_state|threads_max)
        - action: drop
          source_labels: [__name__]
          regex: container_spec.*
        - action: drop
          source_labels: [id, pod]
          regex: .+;

        
     
    
    # kube-proxy
    - job_name: kube-proxy
      honor_labels: true
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
        separator: '/'
        regex: 'kube-system/kube-proxy.+'
        action: keep
      - source_labels:
        - __address__
        regex: (.+?)(\\:\\d+)?
        replacement: $1:10249
        action: replace
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels: 
        - __meta_kubernetes_pod_label_app_kubernetes_io_name
        target_label: job

    # kube-controller-manager
    - job_name: kube-controller-manager
      honor_labels: true
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
        separator: '/'
        regex: 'kube-system/kube-controller-manager.+'
        action: keep
      - source_labels:
        - __address__
        regex: (.+?)(\\:\\d+)?
        replacement: $1:10257
        action: replace
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels: 
        - __meta_kubernetes_pod_label_app_kubernetes_io_name
        target_label: job

    # Autodiscover pod with annotaions
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_init]
        action: drop
        regex: true
      - source_labels: 
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_container_port_number
        action: keep_if_equal
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        regex: "true"
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        regex: (.+)
        action: replace
        target_label: __metrics_path__
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        action: replace
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - source_labels: 
        - __meta_kubernetes_pod_label_app_kubernetes_io_name
        target_label: job

    # Autodiscover endpoint with annotaions
    - job_name: kubernetes-endpoints
      kubernetes_sd_configs:
      - role: endpointslices
      relabel_configs:
      - action: drop
        source_labels: [__meta_kubernetes_pod_container_init]
        regex: "true"
      - action: keep_if_equal
        source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
      - action: keep
        source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        regex: "true"
      - action: replace
        source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        target_label: __scheme__
        regex: (https?)
      - action: replace
        source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        target_label: __metrics_path__
        regex: (.+)
      - action: replace
        source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_service_name]
        target_label: job


    - job_name: node-exporter
      honor_labels: true
      kubernetes_sd_configs:
          - role: endpoints
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
          regex: node-exporter-service
        - action: keep
          source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: http-metrics
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
        - source_labels: [__meta_kubernetes_service_name]
          target_label: job
        - source_labels: [__meta_kubernetes_endpoint_node_name]
          target_label: node


    - job_name: kube-state-metrics
      honor_labels: true
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - action: keep
          source_labels: 
            - __meta_kubernetes_endpoints_label_app_kubernetes_io_name
          regex: kube-state-metrics
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: http-metrics
          action: keep
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_service_name]
          target_label: job

    - job_name: argocd
      honor_labels: true
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
          regex:
          - argocd-metrics
          - argocd-server-metrics
          - argocd-repo-server
          - argocd-applicationset-controller
        - action: keep
          source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: metrics
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
        - source_labels: [__meta_kubernetes_service_name]
          target_label: job

