server:
  image:
    tag: ""
  nameOverride: vmalert
  fullnameOverride: vmalert
  annotations:
   configmap.reloader.stakater.com/reload: "record-rules-config,alert-rules-config"
  datasource:
    url:  "http://vmsingle.monitoring-test.svc.cluster.local:8428"
  remote:
    write:
      url: "http://vmsingle.monitoring-test.svc.cluster.local:8428/api/v1/write"
  notifier:
    alertmanager:
      url: http://vmalert-alertmanager.monitoring-test.svc.cluster.local:9093
  extraArgs:
    rule: /rules/*.yaml
  extraVolumes:
    - name: record-rules
      configMap:
        name: record-rules-config
    - name: alert-rules
      configMap:
        name: alert-rules-config
  extraVolumeMounts:
    - name: record-rules
      mountPath: /rules/record-rules.yaml
      subPath: record-rules.yaml
    - name: alert-rules
      mountPath: /rules/alert-rules.yaml
      subPath: alert-rules.yaml

alertmanager:
  enabled: true
  tag: v0.25.0
  persistentVolume:
    enabled: true
    size: 50Mi
  configMap: ""