server:
  nameOverride: vmalert
  fullnameOverride: vmalert
  datasource:
    url:  http://vmsingle.monitoring.svc.cluster.local:8428
  remote:
    write:
      url:  http://vmsingle.monitoring.svc.cluster.local:8428
  notifier:
    alertmanager:
      url: http://alertmanager.monitoring.svc.cluster.local:8428
  extraArgs:
    rule: /rules/*.yaml
  extraVolumes:
    - name: record-rules
      configMap:
        name: record-rules-config
  extraVolumeMounts:
    - name: record-rules
      mountPath: /rules/record.yaml
      subPath: record.yaml
  # configMap: vmalert-config
  # config:
  #  alerts:
  #    groups:
  #      - name: common
  #        rules:
  #          - alert: instanceIsDown
  #            for: 1m
  #            expr: up == 0
  #            labels:
  #              severity: critical
  #            annotations:
  #              summary: "{{ $labels.job }} instance: {{$labels.instance }} is not up"
  #              description: "Job {{ $labels.job }}  instance: {{$labels.instance }} is not up for the last 1 minute"