server:
  image:
    tag: ""
  nameOverride: vmalert
  fullnameOverride: vmalert
  datasource:
    url:  http://vmsingle.monitoring.svc.cluster.local:8428
  remote:
    write:
      url:  http://vmsingle.monitoring.svc.cluster.local:8428
  notifier:
    alertmanager:
      url: http://vmalert-alertmanager.monitoring.svc.cluster.local:9093
  extraArgs:
    rule: /rules/*.yaml
  extraVolumes:
    - name: record-rules
      configMap:
        name: record-rules-config
  extraVolumeMounts:
    - name: record-rules
      mountPath: /rules/record.yaml
      subPath: record.yaml

alertmanager:
  enabled: true
  tag: v0.25.0
  persistentVolume:
    enabled: true
    size: 50Mi
  configMap: ""