apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: vm
  namespace: monitoring
spec:
  routePrefix: /alertmanager
  replicaCount: 1
  configSecret: vm-alertmanager-config
  selectAllByDefault: true