replicaCount: 1
nameOverride: argocd-image-updater
fullnameOverride: argocd-image-updater
volumeMounts: 
  - mountPath: /etc/ssl/certs/nexus-ca.pem
    name: nexus-ca-certs
    subPath: nexus-ca.pem
volumes: 
- name: nexus-ca-certs
  secret:
    secretName: nexus-ca-certs
registries:
    - name: nexus
      api_url: https://docker.home.local
      ping: no
      credentials: pullsecret:argocd/nexus-secret