apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
  namespace: vault
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - home
  secretName: vault-tls
  dnsNames:
  - "*.dev.local"
  - "*.vault.svc"
  - "*.vault.svc.cluster.local"
  - "*.vault-internal"
  - vault
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
