namespaceOverride: ingress-nginx
controller:
  opentelemetry:
    enabled: true
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  config:
        enable-opentelemetry: true
        otel-sampler: AlwaysOn
        otel-sampler-ratio: "0.1"
        otlp-collector-host: otel-collector.tracing.svc.cluster.local
        otlp-collector-port: "4317"
        opentelemetry-config: "/etc/nginx/opentelemetry.toml"
        opentelemetry-operation-name: "HTTP $request_method $service_name $uri"
        opentelemetry-trust-incoming-span: "true"
        otel-max-queuesize: "2048"
        otel-schedule-delay-millis: "5000"
        otel-max-export-batch-size: "512"
        otel-service-name: "nginx"
        otel-sampler-parent-based: "true"

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - ingress-nginx
          topologyKey: "kubernetes.io/hostname"

  replicaCount: 2
  minAvailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 90Mi

  service:
    enabled: true
    type: LoadBalancer
    

  admissionWebhooks:
    enabled: false

  metrics:
    enabled: true
    service:
      annotations:
       prometheus.io/scrape: "true"
       prometheus.io/port: "10254"

  priorityClassName: "medium-priority"

revisionHistoryLimit: 2