apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: utils
  namespace: argocd
  labels:
    app: utilits
spec:
  sourceRepos:
  - https://github.com/vladoz77/argocd.git
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
