apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc-headless
spec:
  clusterIP: None
  selector:
    app: postgresql-app
  ports:
  - port: 5432
    targetPort: psql

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
spec:
  type: NodePort
  selector:
    app: postgresql-app
  ports:
  - port: 5432
    targetPort: psql
    nodePort: 32543


---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
stringData:
  username: "postgres"
  password: "secret"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-sts
spec:
  selector:
    matchLabels:
      app: postgresql-app
  serviceName: postgresql-svc-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-app
    spec:
      containers:
      - name: postgresql
        image: postgres:16.2
        env:
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name:  pg-secret
                key:  username
          - name: POSTGRES_PASSWORD 
            valueFrom:
              secretKeyRef:
                name:  pg-secret
                key:  password
        resources:
          requests:
            memory: "265Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: psql
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi


