apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi