apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logging
  name: es-client
  labels:
    app: es
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es
      role: client
  template:
    metadata:
      labels:
        app: es
        role: client
    spec:
      containers:
      - name: es-client
        image: elasticsearch:7.17.5
        env:
        - name: cluster.name
          value: es-cluster
        - name: node.name
          value: es-client
        - name: discovery.seed_hosts
          value: es-master.logging,es-data.logging,es-client.logging
        - name: cluster.initial_master_nodes
          value: es-master-0,es-master-1
        - name: node.roles
          value: ingest
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        - name: network.host
          value: "_site_"
        - name: ELASTIC_PASSWORD
          value: "changeme"
        resources: {}
        ports:
        - containerPort: 9200
          name: client
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: "storage"
        emptyDir:
          medium: ""
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
