apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: es-master
  labels:
    app: es
    role: master
spec:
  clusterIP: None
  ports:
  - port: 9300
    name: transport
  selector:
    app: es
    role: master
