apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: logging
  name: es-master
  labels:
    app: es
    role: master
spec:
  serviceName: es-master
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app: es
      role: master
  template:
    metadata:
      labels:
        app: es
        role: master
    spec:
      containers:
      - name: es-master
        image: elasticsearch:7.17.5
        env:
        - name: cluster.name
          value: es-cluster
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: es-master.logging,es-data.logging,es-client.logging
        - name: cluster.initial_master_nodes
          value: es-master-0,es-master-1
        - name: node.roles
          value: master
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        - name: network.host
          value: "_site_"
        - name: xpack.security.enabled
          value: "true"
        - name: ELASTIC_PASSWORD
          value: "changeme"
        ports:
        - containerPort: 9300
          name: transport
        resources: {}
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: "storage"
        emptyDir:
          medium: ""
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
