apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: logging
  name: elasticsearch-master
  labels:
    app: elasticsearch
    role: master
spec:
  serviceName: elasticsearch-master
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      containers:
      - name: elasticsearch-master
        image: elasticsearch:7.17.5
        env:
        - name: cluster.name
          value: elasticsearch
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: elasticsearch-master.logging,elasticsearch-data.logging,elasticsearch-client.logging
        - name: cluster.initial_master_nodes
          value: elasticsearch-master-0 elasticsearch-master-1
        - name: node.roles
          value: master
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        - name: network.host
          value: "_site_"
        ports:
        - containerPort: 9300
          name: transport
        resources: {}
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: "storage"
        emptyDir:
          medium: ""
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
