apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
     - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/vladoz77/argocd.git
      targetRevision: HEAD
      ref: repo
    - repoURL:  https://grafana.github.io/helm-charts
      chart: tempo-distributed
      targetRevision: 1.7.3
      helm:
        valueFiles:
          - $repo/tempo/tempo/tempo-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tempo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true