apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tracing
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: tempo
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true