apiVersion: v1
kind: ConfigMap
metadata:
  namespace: logging
  name: kibana-config
  labels:
    app: kibana
data:
  kibana.yml: |-
    server.host: "::"
    server.port: 5601
    elasticsearch.hosts: [http://es-client:9200]
    server.rewriteBasePath: false
    elasticsearch.username: elastic
    elasticsearch.password: changeme
