apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: loki
    server: 'https://kubernetes.default.svc'
  source:
    path: loki/promtail
    repoURL: 'https://github.com/vladoz77/argocd'
    targetRevision: HEAD
  sources: []
  project: logging
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true