apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-dep
spec:
  template:
    spec:
      containers:
      - name: pgadmin4
        resources:
          requests:
            memory: "265Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"