apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pgadmin
spec:
  storageClassName: longhorn-data
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce