vmselect:
  enabled: true
  replicaCount: 3
  name: vmselect
  fullnameOverride: vmselect
  extraArgs:
    replicationFactor: 3
    dedup.minScrapeInterval: 30s
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8481"
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

vminsert:
  enabled: true
  name: vminsert
  fullnameOverride: vminsert
  replicaCount: 3
  extraArgs:
    replicationFactor: 3
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8480"
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

vmstorage:
  enabled: true
  name: vmstorage
  replicaCount: 3
  fullnameOverride: vmstorage
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8482"
  persistentVolume:
    enabled: true
    storageClass: longhorn-db
    mountPath: /storage
    size: 8Gi
