fullnameOverride: otel-collector
mode: deployment
config:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:14250
        thrift_http:
          endpoint: ${env:MY_POD_IP}:14268
        thrift_compact:
          endpoint: ${env:MY_POD_IP}:6831
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318

  exporters:
    otlp:
      endpoint: tempo-distributor:4317
      tls:
        insecure: true

  service:
    pipelines:
      traces: # here, we add the receivers and exporters accordingly
          exporters:
            - otlp
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - jaeger
      metrics: null
      logs: null
