fullnameOverride: tempo

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  

# Configure S3 backend
storage:
  trace:
    backend: s3
    s3:
      bucket: tempo
      endpoint: minio-svc.minio.svc.cluster.local:9000
      access_key: admin
      secret_key: password
      insecure: true

# # Configure distributor
# distributor:
#   config:
#     log_received_spans:
#       enabled: true


# Disable Minio server installation
minio:
  enabled: false


metricsGenerator:
  enabled: true
  config:
    storage:
      path: /var/tempo/wal
      wal:
      remote_write_flush_deadline: 1m
      remote_write:
       - url: http://vmsingle-vm.monitoring.svc:8429/vm/api/v1/write