---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: admin 
  secretAccessKey: password
  endpoint: http://minio-svc.minio.svc.cluster.local:9000
