apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  volumes:
  - name: csi-volume
    persistentVolumeClaim:
      claimName: csi-s3-pvc
  
  containers:
  - name: pod
    command:
    - sleep
    - "3600"
    image: busybox
    resources: {}
    volumeMounts:
      - name: csi-volume
        mountPath: /tmp
